# Generated by Django 4.1.6 on 2023-02-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcast', '0003_alter_like_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='blog',
            new_name='episode',
        ),
    ]
