# Generated by Django 4.1.6 on 2023-02-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcast', '0004_rename_blog_like_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
