# Generated by Django 4.1.6 on 2023-03-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcast', '0005_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
