# Generated by Django 4.1.6 on 2023-04-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
        ('mypodcast', '0006_episode_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Playmusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypodcast.episode')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypodcast.playlist')),
            ],
        ),
    ]
