# Generated by Django 4.1.6 on 2023-04-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcast', '0008_rename_playmusic_playlistitem_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypodcast.episode'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mypodcast.playlist'),
        ),
    ]
