# Generated by Django 4.1.6 on 2023-04-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcast', '0009_alter_playlistitem_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mypodcast.episode'),
            preserve_default=False,
        ),
    ]
