# Generated by Django 4.1.6 on 2023-04-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypodcast', '0010_alter_playlistitem_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypodcast.episode'),
        ),
    ]
